In [44]:
import numpy as np
np.__version__

'1.26.4'

In [45]:
from numpy import array

a = array([3,4,5])
b = array([8,7,6])
a+b

array([11, 11, 11])

In [46]:
from numpy import array

a = array([3,4,5,7])
b = array([8,7,6])
a*b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [47]:
from numpy import array

a = array([3,4,5])
a

array([3, 4, 5])

In [48]:
b=2
b

2

In [49]:
a+b

array([5, 6, 7])

In [50]:
from numpy import array

A = array([[1,2,3], [1,2,3]])
A

array([[1, 2, 3],
       [1, 2, 3]])

In [51]:
A+2

array([[3, 4, 5],
       [3, 4, 5]])

In [52]:
from numpy import arange

x = arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
y = arange(-1, 2)
y

array([-1,  0,  1])

In [54]:
x*y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [55]:
x+y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [56]:
from numpy import arange

x = arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
y = arange(3,10,3).reshape(3,1)
y

array([[3],
       [6],
       [9]])

In [58]:
x/y

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 0.83333333, 1.        ],
       [0.77777778, 0.88888889, 1.        ]])

In [59]:
x-y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [60]:
from numpy import arange

x = arange(1,4)
x

array([1, 2, 3])

In [61]:
y = arange(1,4).reshape(3,1)
y

array([[1],
       [2],
       [3]])

In [62]:
x*y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [63]:
x-y

array([[ 0,  1,  2],
       [-1,  0,  1],
       [-2, -1,  0]])

In [64]:
from numpy import arange

x = arange(0,10,3).reshape(4,1)
x

array([[0],
       [3],
       [6],
       [9]])

In [65]:
y = arange(1,3)
y

array([1, 2])

In [66]:
x*y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [67]:
x+y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [68]:
from numpy import array

x = array([0,10,20,30])
x

array([ 0, 10, 20, 30])

In [69]:
a = x[None, :]
a

array([[ 0, 10, 20, 30]])

In [70]:
a = x[np.newaxis, :]
a

array([[ 0, 10, 20, 30]])

In [71]:
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [72]:
from numpy import array

b = array([1,2,3])
b

array([1, 2, 3])

In [73]:
a+b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [75]:
a*b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [76]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [78]:
print(x[[2]])
print(x[[2, 3]])

[2]
[2 3]


In [79]:
x[[2, 3, 5, 8]]

array([2, 3, 5, 8])

In [80]:
x[np.array([5, 3, -4, 8])]

array([5, 3, 6, 8])

In [81]:
x[np.array([10])]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [82]:
from numpy import arange

x = arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [83]:
x[0,1]

1

In [84]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [85]:
x[[0], [1]]

array([1])

In [86]:
x[:, [5,4]]

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [87]:
x[[1,3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [88]:
x[[1,3], :]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [89]:
x[[1,3], [2,2]]

array([10, 26])

In [90]:
x[[1,3],[2]]

array([10, 26])

In [91]:
x[[1,3], [3,3]]

array([11, 27])

In [92]:
x[[1,3], [3]]

array([11, 27])

In [93]:
from numpy import array

x[array([0,2,4]), array([0,1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [94]:
x[np.array([0,2,4]), 1]

array([ 1, 17, 33])

In [95]:
print(x[0,1])
print(x[2,1])
print(x[4,1])

1
17
33


In [96]:
from numpy import arange

a = arange(40).reshape(5,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [97]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [98]:
a[arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [99]:
a[arange(2,4)][:, [1,0]]

array([[17, 16],
       [25, 24]])

In [100]:
a[arange(2, 5)][:, [1,0,3,5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [101]:
a[arange(2,5)][:, arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

## 145, 175